import { app, HttpResponseInit, InvocationContext } from '@azure/functions'
import { getPool, sql } from './database.js'

const json = (body: unknown, status = 200): HttpResponseInit => ({ status, jsonBody: body })
const badRequest = (message: string) => json({ message }, 400)
// 对客户端只返回安全的故障类别，绝不回传连接字符串、密码或 SQL 细节。
const serverError = (context: InvocationContext, error: unknown) => {
  context.error(error)
  const detail = error instanceof Error ? error.message : ''
  if (detail.includes('SQL_CONNECTION_STRING')) return json({ message: '数据库连接配置缺失' }, 500)
  if (/login failed|authentication failed/i.test(detail)) return json({ message: '数据库账号或密码无法验证' }, 500)
  if (/firewall|not allowed to access|cannot open server|timeout|connect/i.test(detail)) return json({ message: '数据库网络连接被拒绝或超时' }, 500)
  return json({ message: '服务器暂时无法处理请求' }, 500)
}

app.http('members', { methods: ['GET', 'POST'], authLevel: 'anonymous', route: 'members', handler: async (request, context) => { try { const db = await getPool(); if (request.method === 'GET') { const result = await db.request().query('SELECT id, name FROM members ORDER BY id'); return json(result.recordset) } const { name } = await request.json() as { name?: string }; const trimmed = name?.trim(); if (!trimmed || trimmed.length > 100) return badRequest('名字必须介于 1 至 100 个字符之间'); try { const result = await db.request().input('name', sql.NVarChar(100), trimmed).query('INSERT INTO members (name) OUTPUT INSERTED.id, INSERTED.name VALUES (@name)'); return json(result.recordset[0], 201) } catch (error) { if (error instanceof sql.RequestError && error.number === 2627) { const existing = await db.request().input('name', sql.NVarChar(100), trimmed).query('SELECT id, name FROM members WHERE name=@name'); return json(existing.recordset[0]) } throw error } } catch (error) { return serverError(context, error) } } })

app.http('equipment', { methods: ['GET', 'POST'], authLevel: 'anonymous', route: 'equipment', handler: async (request, context) => { try { const db = await getPool(); if (request.method === 'POST') { const { name, category, description, imageUrl } = await request.json() as { name?: string; category?: string; description?: string; imageUrl?: string }; const cleanName = name?.trim(); if (!cleanName || cleanName.length > 200) return badRequest('器材名称必须介于 1 至 200 个字符之间'); const result = await db.request().input('name', sql.NVarChar(200), cleanName).input('category', sql.NVarChar(100), category?.trim() || '其他').input('description', sql.NVarChar(500), description?.trim() || null).input('imageUrl', sql.NVarChar(500), imageUrl?.trim() || null).query("INSERT INTO equipment (name, category, status, description, image_url) OUTPUT INSERTED.id, INSERTED.name, INSERTED.category, INSERTED.status, INSERTED.description, INSERTED.image_url AS imageUrl VALUES (@name, @category, 'available', @description, @imageUrl)"); return json(result.recordset[0], 201) } const status = request.query.get('status'); if (status && status !== 'available' && status !== 'borrowed') return badRequest('status 必须为 available 或 borrowed'); const query = `SELECT e.id, e.name, e.category, e.status, e.image_url AS imageUrl, e.description, br.id AS borrowId, br.member_id AS memberId, m.name AS memberName, br.borrow_time AS borrowTime FROM equipment e LEFT JOIN borrow_records br ON br.equipment_id = e.id AND br.return_time IS NULL LEFT JOIN members m ON m.id = br.member_id ${status ? 'WHERE e.status = @status' : ''} ORDER BY e.id`; const result = await db.request().input('status', sql.VarChar(20), status).query(query); return json(result.recordset.map((row) => ({ id: row.id, name: row.name, category: row.category, status: row.status, imageUrl: row.imageUrl, description: row.description, activeBorrow: row.borrowId ? { id: row.borrowId, equipmentId: row.id, memberId: row.memberId, memberName: row.memberName, borrowTime: row.borrowTime, returnTime: null } : null }))) } catch (error) { return serverError(context, error) } } })

// 仅允许删除从未借出过且当前可借的器材，避免破坏借还历史与外键关系。
app.http('delete-equipment', { methods: ['DELETE'], authLevel: 'anonymous', route: 'equipment/{id:int}', handler: async (request, context) => { try { const id = Number(request.params.id); if (!Number.isInteger(id) || id < 1) return badRequest('器材编号无效'); const db = await getPool(); const result = await db.request().input('id', sql.Int, id).query("DELETE FROM equipment WHERE id=@id AND status='available' AND NOT EXISTS (SELECT 1 FROM borrow_records WHERE equipment_id=@id)"); if (result.rowsAffected[0] !== 1) return json({ message: '器材不存在、正在借出，或已有借还历史，无法删除' }, 409); return json({ ok: true }) } catch (error) { return serverError(context, error) } } })

app.http('borrow-records', { methods: ['GET'], authLevel: 'anonymous', route: 'borrow-records', handler: async (request, context) => { try { const memberId = Number(request.query.get('memberId')); const active = request.query.get('active') === 'true'; const db = await getPool(); if (memberId && active) { const result = await db.request().input('memberId', sql.Int, memberId).query(`SELECT e.id, e.name, e.category, e.status, e.image_url AS imageUrl, e.description, br.id AS borrowId, br.member_id AS memberId, m.name AS memberName, br.borrow_time AS borrowTime FROM borrow_records br JOIN equipment e ON e.id=br.equipment_id JOIN members m ON m.id=br.member_id WHERE br.member_id=@memberId AND br.return_time IS NULL ORDER BY br.borrow_time DESC`); return json(result.recordset.map((row) => ({ id: row.id, name: row.name, category: row.category, status: row.status, imageUrl: row.imageUrl, description: row.description, activeBorrow: { id: row.borrowId, equipmentId: row.id, memberId: row.memberId, memberName: row.memberName, borrowTime: row.borrowTime, returnTime: null } }))) } const result = await db.request().query('SELECT id, equipment_id AS equipmentId, member_id AS memberId, borrow_time AS borrowTime, return_time AS returnTime FROM borrow_records ORDER BY borrow_time DESC'); return json(result.recordset) } catch (error) { return serverError(context, error) } } })

app.http('borrow', { methods: ['POST'], authLevel: 'anonymous', route: 'borrow', handler: async (request, context) => { try { const { equipmentId, memberId } = await request.json() as { equipmentId?: number; memberId?: number }; if (!Number.isInteger(equipmentId) || !Number.isInteger(memberId)) return badRequest('equipmentId 和 memberId 必须是整数'); const db = await getPool(); const transaction = new sql.Transaction(db); await transaction.begin(sql.ISOLATION_LEVEL.SERIALIZABLE); try { const member = await new sql.Request(transaction).input('memberId', sql.Int, memberId).query('SELECT id FROM members WHERE id=@memberId'); if (!member.recordset[0]) { await transaction.rollback(); return json({ message: '成员不存在' }, 404) } const updated = await new sql.Request(transaction).input('equipmentId', sql.Int, equipmentId).query("UPDATE equipment WITH (UPDLOCK, ROWLOCK) SET status='borrowed' WHERE id=@equipmentId AND status='available'"); if (updated.rowsAffected[0] !== 1) { await transaction.rollback(); return json({ message: '器材不存在或已被借出' }, 409) } const record = await new sql.Request(transaction).input('equipmentId', sql.Int, equipmentId).input('memberId', sql.Int, memberId).query('INSERT INTO borrow_records (equipment_id, member_id, borrow_time) OUTPUT INSERTED.id, INSERTED.borrow_time AS borrowTime VALUES (@equipmentId, @memberId, SYSUTCDATETIME())'); await transaction.commit(); return json(record.recordset[0], 201) } catch (error) { await transaction.rollback(); throw error } } catch (error) { return serverError(context, error) } } })

app.http('return', { methods: ['POST'], authLevel: 'anonymous', route: 'return', handler: async (request, context) => { try { const { borrowRecordId, memberId } = await request.json() as { borrowRecordId?: number; memberId?: number }; if (!Number.isInteger(borrowRecordId) || !Number.isInteger(memberId)) return badRequest('borrowRecordId 和 memberId 必须是整数'); const db = await getPool(); const transaction = new sql.Transaction(db); await transaction.begin(); try { const record = await new sql.Request(transaction).input('id', sql.Int, borrowRecordId).input('memberId', sql.Int, memberId).query('UPDATE borrow_records SET return_time=SYSUTCDATETIME() OUTPUT INSERTED.equipment_id AS equipmentId WHERE id=@id AND member_id=@memberId AND return_time IS NULL'); if (!record.recordset[0]) { await transaction.rollback(); return json({ message: '未找到有效的借用记录' }, 404) } await new sql.Request(transaction).input('equipmentId', sql.Int, record.recordset[0].equipmentId).query("UPDATE equipment SET status='available' WHERE id=@equipmentId"); await transaction.commit(); return json({ ok: true }) } catch (error) { await transaction.rollback(); throw error } } catch (error) { return serverError(context, error) } } })
