import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { addEquipment, archiveTask, borrowEquipment, borrowKit, createKit, createMember, createTask, deleteEquipment, deleteKit, deleteTask, getBorrowHistory, getEquipment, getKits, getMemberBorrowHistory, getMembers, getMyBorrowings, getTasks, joinTask, leaveTask, returnEquipment, returnKit, updateEquipment, updateKit, updateTask } from './api'
import type { BorrowRecord, Equipment, EquipmentInput, Kit, KitInput, Member, TaskInput, TeamTask } from './types'
import logo from './assets/zje-lens-logo.png'
import './App.css'

type View = 'all' | 'available' | 'borrowed' | 'mine' | 'my-tasks' | 'tasks' | 'history' | 'task-history' | 'task-records'
type PrimaryTab = 'equipment' | 'tasks' | 'records' | 'mine'
type CategoryFilter = 'all' | 'camera' | 'lens' | 'accessory'
const primaryTabs: { key: PrimaryTab; label: string; view: View }[] = [{ key: 'equipment', label: '器材', view: 'all' }, { key: 'tasks', label: '任务', view: 'tasks' }, { key: 'records', label: '记录', view: 'history' }, { key: 'mine', label: '我的', view: 'mine' }]
const primaryForView = (view: View): PrimaryTab => ['all', 'available', 'borrowed'].includes(view) ? 'equipment' : ['tasks', 'task-history'].includes(view) ? 'tasks' : ['history', 'task-records'].includes(view) ? 'records' : 'mine'
const categoryFilters: { key: CategoryFilter; label: string }[] = [{ key: 'all', label: '全部' }, { key: 'camera', label: '相机' }, { key: 'lens', label: '镜头' }, { key: 'accessory', label: '配件' }]
const categoryOrder = ['相机', '镜头', '麦克风', '存储卡', '提词器', '三脚架', '电池', '滤镜', '监看器', '读卡器', '其他']
const categoryRank = (category: string) => { const index = categoryOrder.indexOf(category); return index < 0 ? categoryOrder.length : index }
const formatTime = (value: string) => new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const formatTaskTime = (value: string | null) => value ? formatTime(value) : '时间待补充'
const toDateTimeLocal = (value: string | null) => { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) }
const readStoredUser = (): Member | null => { const id = Number(localStorage.getItem('currentUserId')); const name = localStorage.getItem('currentUserName')?.trim(); return Number.isInteger(id) && id > 0 && name ? { id, name } : null }

function App() {
  const [equipment, setEquipment] = useState<Equipment[]>([]); const [kits, setKits] = useState<Kit[]>([]); const [history, setHistory] = useState<BorrowRecord[]>([]); const [tasks, setTasks] = useState<TeamTask[]>([]); const [currentUser, setCurrentUser] = useState<Member | null>(readStoredUser); const [view, setView] = useState<View>('all'); const [categoryFilter, setCategoryFilter] = useState<CategoryFilter>('all'); const [loading, setLoading] = useState(true); const [startupMessage, setStartupMessage] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [userMenuOpen, setUserMenuOpen] = useState(false); const [adding, setAdding] = useState(false); const [addingKit, setAddingKit] = useState(false); const [editingEquipment, setEditingEquipment] = useState<Equipment | null>(null); const [editingKit, setEditingKit] = useState<Kit | null>(null); const [managing, setManaging] = useState(false); const [taskManaging, setTaskManaging] = useState(false); const [taskEditor, setTaskEditor] = useState<TeamTask | 'new' | null>(null)
  async function loadData(user?: Member | null, attempt = 0) {
    if (attempt === 0) { setLoading(true); setError(''); setStartupMessage('') }
    try {
      const storedMemberId = user?.id ?? Number(localStorage.getItem('currentUserId'))
      if (view === 'my-tasks') {
        const [allMembers, activeTasks, archivedTasks] = await Promise.all([getMembers(), getTasks(false), getTasks(true)])
        const saved = user ?? allMembers.find((member) => member.id === storedMemberId) ?? null
        setCurrentUser(saved)
        setTasks(saved ? [...activeTasks, ...archivedTasks].filter((task) => task.participants.some((participant) => participant.memberId === saved.id)) : [])
        setEquipment([]); setKits([])
      } else if (['tasks', 'task-history', 'task-records'].includes(view)) {
        const archived = view === 'task-history' || view === 'task-records'
        const [allMembers, taskList] = await Promise.all([getMembers(), getTasks(archived)])
        const saved = user ?? allMembers.find((member) => member.id === storedMemberId) ?? null
        setCurrentUser(saved); setTasks(taskList); setEquipment([]); setKits([])
      } else if (view === 'history') {
        const [allMembers, records] = await Promise.all([getMembers(), getBorrowHistory()])
        const saved = user ?? allMembers.find((member) => member.id === storedMemberId) ?? null
        setCurrentUser(saved); setHistory(records); setEquipment([]); setKits([])
      } else if (view === 'mine') {
        const [allMembers, myEquipment, allKits, records] = await Promise.all([
          getMembers(),
          storedMemberId > 0 ? getMyBorrowings(storedMemberId) : Promise.resolve([]),
          getKits(),
          storedMemberId > 0 ? getMemberBorrowHistory(storedMemberId) : Promise.resolve([]),
        ])
        const saved = user ?? allMembers.find((member) => member.id === storedMemberId) ?? null
        setCurrentUser(saved); setEquipment(myEquipment); setKits(allKits); setHistory(records.filter((record) => Boolean(record.returnTime)))
      } else {
        const [allMembers, allEquipment, allKits] = await Promise.all([getMembers(), getEquipment(), getKits()])
        const saved = user ?? allMembers.find((member) => member.id === storedMemberId) ?? null
        setCurrentUser(saved); setEquipment(allEquipment); setKits(allKits)
      }
      setStartupMessage('')
    } catch {
      if (attempt < 11) { setStartupMessage('系统正在启动，首次加载可能需要约一分钟，请稍候，页面会自动重试。'); await new Promise((resolve) => window.setTimeout(resolve, 5000)); return loadData(user, attempt + 1) }
      setStartupMessage(''); setError('系统启动时间较长，请刷新页面后重试。')
    } finally { if (attempt === 0) setLoading(false) }
  }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void loadData(currentUser) }, [view])
  const displayed = useMemo(() => equipment.filter((item) => { const statusMatches = view === 'available' ? item.availableQuantity > 0 : view === 'borrowed' ? item.activeBorrowCount > 0 : true; const categoryMatches = categoryFilter === 'all' || categoryFilter === 'camera' && item.category === '相机' || categoryFilter === 'lens' && item.category === '镜头' || categoryFilter === 'accessory' && item.category !== '相机' && item.category !== '镜头'; return statusMatches && categoryMatches }).sort((a, b) => view === 'mine' ? 0 : categoryRank(a.category) - categoryRank(b.category) || a.name.localeCompare(b.name, 'zh-CN')), [equipment, view, categoryFilter])
  function message(value: string) { setNotice(value); window.setTimeout(() => setNotice(''), 3200) }
  function chooseUser(member: Member) { localStorage.setItem('currentUserId', String(member.id)); localStorage.setItem('currentUserName', member.name); setCurrentUser(member); message(`你好，${member.name}！`) }
  function switchUser() { localStorage.removeItem('currentUserId'); localStorage.removeItem('currentUserName'); setCurrentUser(null); setView('all'); setManaging(false); setTaskManaging(false); setUserMenuOpen(false) }
  function changeView(next: View) { setView(next); setManaging(false); setTaskManaging(false); setUserMenuOpen(false); if (!['all', 'available', 'borrowed'].includes(next)) setCategoryFilter('all') }
  function toggleManagement() { const next = !managing; setManaging(next); if (next) setView('all') }
  async function borrow(item: Equipment) { if (!currentUser) return; try { await borrowEquipment(item.id, currentUser.id); message(`已借出：${item.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '借出失败，请重试') } }
  async function returnItem(item: Equipment) { if (!currentUser || !item.activeBorrow) return; try { await returnEquipment(item.activeBorrow.id, currentUser.id); message(`已归还：${item.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '归还失败，请重试') } }
  async function saveEquipment(input: EquipmentInput) { try { const item = await addEquipment(input); setAdding(false); message(`已录入：${item.name}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('录入失败，请重试') } }
  async function saveEquipmentEdit(input: EquipmentInput) { if (!editingEquipment) return; try { const item = await updateEquipment(editingEquipment.id, input); setEditingEquipment(null); message(`已更新：${item.name}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('更新失败，请重试') } }
  async function saveKit(input: KitInput) { try { const kit = await createKit(input); setAddingKit(false); message(`已录入 Kit：${kit.name}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('录入 Kit 失败，请重试') } }
  async function saveKitEdit(input: KitInput) { if (!editingKit) return; try { const kit = await updateKit(editingKit.id, input); setEditingKit(null); message(`已更新 Kit：${kit.name}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('更新 Kit 失败，请重试') } }
  async function borrowWholeKit(kit: Kit) { if (!currentUser) return; try { await borrowKit(kit.id, currentUser.id); message(`已借出 Kit：${kit.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '借出 Kit 失败，请重试') } }
  async function returnWholeKit(kit: Kit) { if (!currentUser || !kit.activeBorrow) return; try { await returnKit(kit.activeBorrow.id, currentUser.id); message(`已归还 Kit：${kit.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '归还 Kit 失败，请重试') } }
  async function removeEquipment(item: Equipment) { if (!window.confirm(`确定删除“${item.name}”吗？此操作无法撤销。`)) return; try { await deleteEquipment(item.id); message(`已删除：${item.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '删除失败，请重试') } }
  async function removeKit(kit: Kit) { if (!window.confirm(`确定删除 Kit“${kit.name}”吗？此操作无法撤销。`)) return; try { await deleteKit(kit.id); message(`已删除 Kit：${kit.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '删除 Kit 失败，请重试') } }
  async function archive(task: TeamTask) { if (!window.confirm(`确定归档“${task.title}”吗？归档后会移到“任务记录”。`)) return; try { await archiveTask(task.id); message(`已归档：${task.title}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '归档失败，请重试') } }
  async function removeTask(task: TeamTask) { if (!window.confirm(`确定删除“${task.title}”吗？任务和参与名单都会被删除，无法撤销。`)) return; try { await deleteTask(task.id); message(`已删除：${task.title}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '删除失败，请重试') } }
  async function saveTask(input: TaskInput, task?: TeamTask) { if (!currentUser) return; try { const saved = task ? await updateTask(task.id, input) : await createTask(input, currentUser.id); setTaskEditor(null); message(task ? `已更新：${saved.title}` : `已发布：${saved.title}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('保存任务失败，请重试') } }
  async function participate(task: TeamTask) { if (!currentUser) return; try { await joinTask(task.id, currentUser.id); message(`已参与：${task.title}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '参与失败，请重试') } }
  async function cancelParticipation(task: TeamTask) { if (!currentUser) return; try { await leaveTask(task.id, currentUser.id); message(`已取消参与：${task.title}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '取消参与失败，请重试') } }
  if (!currentUser && !loading) return <IdentityPicker onRegistered={chooseUser} />
  const primary = primaryForView(view)
  const taskContent = ['tasks', 'task-history', 'task-records', 'my-tasks'].includes(view)
  const archivedTasks = view === 'task-history' || view === 'task-records'
  const pageTitle = primary === 'equipment' ? '器材管理' : primary === 'tasks' ? '团队任务' : primary === 'records' ? '记录' : '我的'
  const secondaryTabs: { key: View; label: string }[] = primary === 'equipment' ? [{ key: 'all', label: '全部' }, { key: 'available', label: '可借' }, { key: 'borrowed', label: '已借出' }] : primary === 'tasks' ? [{ key: 'tasks', label: '进行中' }, { key: 'task-history', label: '已归档' }] : primary === 'records' ? [{ key: 'history', label: '借还记录' }, { key: 'task-records', label: '任务记录' }] : [{ key: 'mine', label: '器材借用' }, { key: 'my-tasks', label: '参与任务' }]
  return <main className={`app-shell ${primary === 'records' ? 'records-page' : ''}`}>
    <header>
      <div className="header-title"><img className="site-logo" src={logo} alt="ZJE-Lens" /><h1 key={pageTitle}>{pageTitle}</h1></div>
      {currentUser && <div className="user-area">
        {view === 'tasks' && <button className="add-link" onClick={() => setTaskEditor('new')}>＋ 发布</button>}
        <div className="user-stack"><div className="header-menu-wrap"><button className="identity-menu-button" onClick={() => setUserMenuOpen(!userMenuOpen)}>{currentUser.name}<span>⌄</span></button>{userMenuOpen && <div className="header-popover user-popover"><small>当前身份</small><b>{currentUser.name}</b><button onClick={switchUser}>切换身份</button></div>}</div>{(primary === 'equipment' || view === 'tasks') && <button className="manage-link" onClick={() => primary === 'equipment' ? toggleManagement() : setTaskManaging(!taskManaging)}>{primary === 'equipment' ? managing ? '完成管理' : '管理器材' : taskManaging ? '完成管理' : '管理任务'}</button>}</div>
      </div>}
    </header>
    <nav className="primary-nav" aria-label="主导航">{primaryTabs.map((item) => <button key={item.key} className={primary === item.key ? 'selected' : ''} onClick={() => changeView(item.view)}>{item.label}</button>)}</nav>
    <div className="secondary-nav" aria-label="页面分类">{secondaryTabs.map((item) => <button key={item.key} className={view === item.key ? 'selected' : ''} onClick={() => changeView(item.key)}>{item.label}</button>)}</div>
    {primary === 'equipment' && <div className="category-filters" aria-label="器材类别筛选">{categoryFilters.map((item) => <button key={item.key} className={categoryFilter === item.key ? 'selected' : ''} onClick={() => setCategoryFilter(item.key)}>{item.label}</button>)}</div>}
    {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="关闭提示">×</button></div>}
    {startupMessage && <div className="startup-notice" role="status"><span className="startup-dot" />{startupMessage}</div>}
    {error && <div className="error">{error}</div>}
    {managing && <div className="management-note">管理模式：可编辑器材和 Kit；仅可删除从未借出过的器材或 Kit。</div>}
    {taskManaging && <div className="management-note">任务管理模式：可归档已完成任务，或删除布置错误的任务。</div>}
    <section className="view-content" key={`${view}-${categoryFilter}`}>
      {taskContent ? <TaskBoard tasks={tasks} loading={loading} currentUser={currentUser} archived={archivedTasks} mine={view === 'my-tasks'} managing={taskManaging} onJoin={participate} onLeave={cancelParticipation} onEdit={setTaskEditor} onArchive={archive} onDelete={removeTask} /> : <EquipmentPage view={view} displayed={displayed} kits={kits} currentUser={currentUser} categoryFilter={categoryFilter} history={history} loading={loading} managing={managing} onAddEquipment={() => setAdding(true)} onAddKit={() => setAddingKit(true)} onBorrow={borrow} onReturn={returnItem} onBorrowKit={borrowWholeKit} onReturnKit={returnWholeKit} onEdit={setEditingEquipment} onDelete={removeEquipment} onEditKit={setEditingKit} onDeleteKit={removeKit} />}
    </section>
    {adding && <AddEquipmentDialog onClose={() => setAdding(false)} onSave={saveEquipment} />}
    {addingKit && <AddKitDialog equipment={equipment} onClose={() => setAddingKit(false)} onSave={saveKit} />}
    {editingEquipment && <AddEquipmentDialog item={editingEquipment} onClose={() => setEditingEquipment(null)} onSave={saveEquipmentEdit} />}
    {editingKit && <AddKitDialog kit={editingKit} equipment={equipment} onClose={() => setEditingKit(null)} onSave={saveKitEdit} />}
    {taskEditor && <TaskDialog task={taskEditor === 'new' ? undefined : taskEditor} onClose={() => setTaskEditor(null)} onSave={saveTask} />}
  </main>
}
function EquipmentPage({ view, displayed, kits, currentUser, categoryFilter, history, loading, managing, onAddEquipment, onAddKit, onBorrow, onReturn, onBorrowKit, onReturnKit, onEdit, onDelete, onEditKit, onDeleteKit }: { view: View; displayed: Equipment[]; kits: Kit[]; currentUser: Member | null; categoryFilter: CategoryFilter; history: BorrowRecord[]; loading: boolean; managing: boolean; onAddEquipment: () => void; onAddKit: () => void; onBorrow: (item: Equipment) => void; onReturn: (item: Equipment) => void; onBorrowKit: (kit: Kit) => void; onReturnKit: (kit: Kit) => void; onEdit: (item: Equipment) => void; onDelete: (item: Equipment) => void; onEditKit: (kit: Kit) => void; onDeleteKit: (kit: Kit) => void }) {
  const historyPage = view === 'history'
  const displayedKits = view === 'all' && categoryFilter === 'all' ? kits : view === 'mine' ? kits.filter((kit) => kit.activeBorrow?.memberId === currentUser?.id) : []
  const equipmentCards = <section className="equipment-grid">{displayed.map((item) => <EquipmentCard key={`${item.id}-${item.activeBorrow?.id ?? 'all'}`} item={item} mine={view === 'mine'} managing={managing} onBorrow={() => onBorrow(item)} onReturn={() => onReturn(item)} onEdit={() => onEdit(item)} onDelete={() => onDelete(item)} />)}</section>
  const currentBorrowings = <>{displayedKits.length > 0 && <><p className="kit-heading first">Kit</p><section className="kit-grid">{displayedKits.map((kit) => <KitCard key={kit.id} kit={kit} mine={view === 'mine'} managing={managing} onBorrow={() => onBorrowKit(kit)} onReturn={() => onReturnKit(kit)} onEdit={() => onEditKit(kit)} onDelete={() => onDeleteKit(kit)} />)}</section></>}{displayed.length > 0 && displayedKits.length > 0 && <p className="equipment-heading">单件器材</p>}{displayed.length > 0 && equipmentCards}</>
  const allEquipment = <>{categoryFilter === 'all' && <><div className="equipment-section-title first"><span>Kit</span><button type="button" onClick={onAddKit} aria-label="录入 Kit">+</button></div>{displayedKits.length > 0 && <section className="kit-grid">{displayedKits.map((kit) => <KitCard key={kit.id} kit={kit} mine={false} managing={managing} onBorrow={() => onBorrowKit(kit)} onReturn={() => onReturnKit(kit)} onEdit={() => onEditKit(kit)} onDelete={() => onDeleteKit(kit)} />)}</section>}</>}<div className={`equipment-section-title ${categoryFilter === 'all' ? '' : 'first'}`}><span>单件器材</span><button type="button" onClick={onAddEquipment} aria-label="录入单件器材">+</button></div>{displayed.length > 0 && equipmentCards}</>

  if (view === 'mine') return <>{loading ? <p className="loading">正在读取器材…</p> : <><section className="personal-section"><div className="personal-section-title"><h2>正在借用</h2><span>{displayed.length + displayedKits.length} 件</span></div>{displayed.length > 0 || displayedKits.length > 0 ? currentBorrowings : <div className="empty compact-empty">你目前没有借用中的器材或 Kit。</div>}</section><section className="personal-section"><div className="personal-section-title"><h2>借用记录</h2><span>{history.length} 条</span></div>{history.length > 0 ? <BorrowHistoryTable records={history} showMember={false} /> : <div className="empty compact-empty">你还没有已归还的器材。</div>}</section></>}</>

  return <><section className="summary compact"><strong>{loading ? '—' : historyPage ? history.length : displayed.length + displayedKits.length} {historyPage ? '条记录' : '件'}</strong></section>{loading ? <p className="loading">正在读取器材…</p> : historyPage ? <BorrowHistoryTable records={history} /> : view === 'all' ? allEquipment : currentBorrowings}{!loading && historyPage && history.length === 0 && <div className="empty">暂时没有借还记录。</div>}{!loading && !historyPage && view !== 'all' && displayed.length === 0 && displayedKits.length === 0 && <div className="empty">这里暂时没有器材。</div>}</>
}
function IdentityPicker({ onRegistered }: { onRegistered: (member: Member) => void }) { const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function register(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onRegistered(await createMember(name)) } catch (reason) { setError(reason instanceof Error ? reason.message : '注册失败，请稍后重试') } finally { setBusy(false) } } return <main className="identity-page"><section className="identity-card"><img className="site-logo" src={logo} alt="ZJE-Lens" /><h1>输入你的名字</h1><p>第一次输入会自动创建账号；以后输入相同名字即可继续。<br />这台设备会记住你的身份，你随时可以在首页切换。</p><form className="register-form single-login" onSubmit={register}><label htmlFor="new-member-name">名字 / 账号名</label><div><input id="new-member-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={100} placeholder="请输入你的名字" autoFocus /><button disabled={busy}>{busy ? '处理中…' : '继续'}</button></div>{error && <p role="alert">{error}</p>}</form></section></main> }
function BorrowHistoryTable({ records, showMember = true }: { records: BorrowRecord[]; showMember?: boolean }) { return <div className="history-table-wrap"><table className="history-table"><thead><tr><th>器材</th><th>类别</th>{showMember && <th>借用人</th>}<th>借出时间</th><th>归还时间</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{record.equipmentName ?? `器材 #${record.equipmentId}`}</td><td>{record.equipmentCategory ?? '—'}</td>{showMember && <td>{record.memberName}</td>}<td>{formatTime(record.borrowTime)}</td><td>{record.returnTime ? formatTime(record.returnTime) : <span className="record-active">借用中</span>}</td></tr>)}</tbody></table></div> }
function TaskBoard({ tasks, loading, currentUser, archived, mine, managing, onJoin, onLeave, onEdit, onArchive, onDelete }: { tasks: TeamTask[]; loading: boolean; currentUser: Member | null; archived: boolean; mine: boolean; managing: boolean; onJoin: (task: TeamTask) => void; onLeave: (task: TeamTask) => void; onEdit: (task: TeamTask) => void; onArchive: (task: TeamTask) => void; onDelete: (task: TeamTask) => void }) {
  const renderTasks = (items: TeamTask[], areArchived: boolean) => <section className="task-grid">{items.map((task) => <TaskCard key={task.id} task={task} currentUser={currentUser} archived={areArchived} managing={managing} onJoin={() => onJoin(task)} onLeave={() => onLeave(task)} onEdit={() => onEdit(task)} onArchive={() => onArchive(task)} onDelete={() => onDelete(task)} />)}</section>
  if (mine) {
    const activeTasks = tasks.filter((task) => !task.archivedAt)
    const archivedTasks = tasks.filter((task) => Boolean(task.archivedAt))
    return loading ? <p className="loading">正在读取任务…</p> : <><section className="personal-section"><div className="personal-section-title"><h2>正在参与</h2><span>{activeTasks.length} 项</span></div>{activeTasks.length > 0 ? renderTasks(activeTasks, false) : <div className="empty compact-empty">你目前还没有参与进行中的任务。</div>}</section><section className="personal-section"><div className="personal-section-title"><h2>参与记录</h2><span>{archivedTasks.length} 项</span></div>{archivedTasks.length > 0 ? renderTasks(archivedTasks, true) : <div className="empty compact-empty">你还没有已归档的参与记录。</div>}</section></>
  }
  return <><section className="summary compact"><strong>{loading ? '—' : tasks.length} 项</strong></section>{loading ? <p className="loading">正在读取任务…</p> : renderTasks(tasks, archived)}{!loading && tasks.length === 0 && <div className="empty">{archived ? '暂时没有已归档的任务。' : '暂时没有团队任务。点击右上角“发布”创建第一项任务。'}</div>}</>
}
function TaskCard({ task, currentUser, archived, managing, onJoin, onLeave, onEdit, onArchive, onDelete }: { task: TeamTask; currentUser: Member | null; archived: boolean; managing: boolean; onJoin: () => void; onLeave: () => void; onEdit: () => void; onArchive: () => void; onDelete: () => void }) { const joined = task.participants.some((participant) => participant.memberId === currentUser?.id); return <article className="task-card"><div className="task-card-top"><div><p className="task-label">{archived ? '已归档任务' : '团队任务'}</p><h2>{task.title}</h2></div>{!archived && !managing && <button className="task-edit" onClick={onEdit}>编辑</button>}</div><dl className="task-details"><div><dt>时间</dt><dd>{formatTaskTime(task.taskTime)}</dd></div><div><dt>地点</dt><dd>{task.location || '地点待补充'}</dd></div></dl>{task.note && <p className="task-note">{task.note}</p>}<div className="participants"><span>参与人员 · {task.participants.length} 人</span><div className="participant-list">{task.participants.length ? task.participants.map((participant) => <i key={participant.memberId}>{participant.memberName}</i>) : <em>暂无参与者</em>}</div></div><div className="task-equipment"><span>任务器材 · {task.equipment.length} 件</span><div>{task.equipment.length ? task.equipment.map((item, index) => <p key={`${item.equipmentId}-${item.memberId}-${index}`}><b>{item.equipmentName}</b><small>{item.memberName} · {item.equipmentCategory}</small></p>) : <em>参与者当前没有借用器材</em>}</div></div>{!archived && <div className="task-actions">{managing ? <><button className="archive-task" onClick={onArchive}>归档任务</button><button className="delete-task" onClick={onDelete}>删除任务</button></> : <button className={joined ? 'joined cancel-task' : ''} onClick={joined ? onLeave : onJoin}>{joined ? '取消参与' : '参与任务'}</button>}</div>}</article> }
function TaskDialog({ task, onClose, onSave }: { task?: TeamTask; onClose: () => void; onSave: (input: TaskInput, task?: TeamTask) => Promise<void> }) { const [title, setTitle] = useState(task?.title ?? ''); const [taskTime, setTaskTime] = useState(toDateTimeLocal(task?.taskTime ?? null)); const [location, setLocation] = useState(task?.location ?? ''); const [note, setNote] = useState(task?.note ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ title, taskTime: taskTime ? new Date(taskTime).toISOString() : null, location, note }, task) } catch (reason) { setError(reason instanceof Error ? reason.message : '保存任务失败') } finally { setBusy(false) } } return <div className="dialog-backdrop" onMouseDown={onClose}><form className="equipment-form task-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="form-title"><h2>{task ? '编辑任务' : '发布新任务'}</h2><button type="button" onClick={onClose}>×</button></div><label>任务名称 <b>必填</b><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例如：周末外拍" maxLength={200} autoFocus /></label><label>任务时间 <small>可选，可后续补充</small><input type="datetime-local" value={taskTime} onChange={(event) => setTaskTime(event.target.value)} /></label><label>任务地点 <small>可选，可后续补充</small><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="例如：西湖断桥" maxLength={200} /></label><label>备注 <small>可选，可后续补充</small><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="说明任务内容、准备事项等" maxLength={1000} /></label>{error && <p className="form-error">{error}</p>}<button className="submit-equipment" disabled={busy}>{busy ? '正在保存…' : task ? '保存修改' : '发布任务'}</button></form></div> }
function EquipmentIcon({ category }: { category: string }) { if (category === '相机') return <svg viewBox="0 0 80 64" aria-hidden="true"><path d="M16 18h13l5-8h12l5 8h13c5 0 8 3 8 8v24c0 5-3 8-8 8H16c-5 0-8-3-8-8V26c0-5 3-8 8-8Z" /><circle cx="40" cy="38" r="13" /><path d="M61 28h1" /></svg>; if (category === '镜头') return <svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="23" /><path d="m37.4 22.7 13.2 22.9M26.6 22.7H53M21.3 32l13.2-22.9M26.6 41.3 13.4 18.4M37.4 41.3H11M42.7 32 29.5 54.9" /></svg>; if (category === '麦克风') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="29" y="8" width="22" height="32" rx="11" /><path d="M21 29v2a19 19 0 0 0 38 0v-2M40 50v8M29 58h22" /></svg>; if (['存储卡', 'SD卡', 'SD 卡', '内存卡'].includes(category)) return <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M19 7h24l9 9v41H19V7Z" /><path d="M27 7v12M35 7v12M43 7v12M25 31h21M25 40h21" /></svg>; if (category === '提词器') return <svg viewBox="0 0 80 64" aria-hidden="true"><path d="M8 29h17v13H8zM4 33h4M25 25l12-12h20l14 29H35L25 25Z" /><path d="m38 18 15 0 10 20H42L38 18Z" /><path d="M43 42v9M30 51h29" /></svg>; if (category === '三脚架') return <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M24 14h16M32 14v7M32 27v12M32 39 16 57M32 39v18M32 39l16 18" /><circle cx="32" cy="24" r="3" /></svg>; if (category === '电池') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="12" y="16" width="54" height="32" rx="4" /><path d="M66 26h5v12h-5M24 25v14M34 25v14M44 25v14M54 25v14" /></svg>; if (category === '滤镜') return <svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="22" /><circle cx="32" cy="32" r="18" /></svg>; if (['监看器', '显示器', '监视器'].includes(category)) return <svg viewBox="0 0 80 64" aria-hidden="true"><path d="m24 16-6-8M56 16l6-8M13 16h54v34H13zM19 22h35v21H19zM60 24h1M60 32h1M60 40h1M40 50v7" /><circle cx="40" cy="58" r="1" /></svg>; if (category === '读卡器') return <svg viewBox="0 0 80 64" aria-hidden="true"><path d="M14 29h43v21H14zM57 35h10v9H57M26 8h17l6 6v21H26V8Z" /><path d="M32 8v10M38 8v10M44 8v10M24 42h22" /></svg>; return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="12" y="16" width="56" height="34" rx="3" /><path d="M12 26h56M28 16v34" /></svg> }
function EquipmentCard({ item, mine, managing, onBorrow, onReturn, onEdit, onDelete }: { item: Equipment; mine: boolean; managing: boolean; onBorrow: () => void; onReturn: () => void; onEdit: () => void; onDelete: () => void }) { const available = item.availableQuantity > 0; const hasBorrow = item.activeBorrowCount > 0; const borrowerNames = [...new Set((item.activeBorrows ?? (item.activeBorrow ? [item.activeBorrow] : [])).map((record) => record.memberName))].join('、'); return <article className="equipment-card"><div className="card-icon"><EquipmentIcon category={item.category} /></div><div className="card-top"><div><p className="category">{item.category} · 共 {item.quantity} 件</p><h2>{item.name}</h2></div><span className={`status ${mine || !available ? 'borrowed' : 'available'}`}>{mine ? '● 借用中' : available ? `● 可借 ${item.availableQuantity} / ${item.quantity}` : '● 已借出'}</span></div>{item.description && <p className="description">{item.description}</p>}{mine && item.activeBorrow ? <div className="borrow-details"><span>借出时间：{formatTime(item.activeBorrow.borrowTime)}</span></div> : hasBorrow && <div className="borrow-details"><span>借出中：{item.activeBorrowCount} 件</span>{borrowerNames && <span>借用人：{borrowerNames}</span>}</div>}<div className="card-action">{managing ? <><button className="edit" onClick={onEdit}>编辑器材</button><button className="delete" onClick={onDelete}>删除器材</button></> : mine && item.activeBorrow && !item.activeBorrow.kitBorrowRecordId ? <button className="return" onClick={onReturn}>归还器材</button> : mine && item.activeBorrow ? <span>属于 Kit，需整套归还</span> : available ? <button onClick={onBorrow}>借出 1 件</button> : <span>暂不可借</span>}</div></article> }
function KitCard({ kit, mine, managing, onBorrow, onReturn, onEdit, onDelete }: { kit: Kit; mine: boolean; managing: boolean; onBorrow: () => void; onReturn: () => void; onEdit: () => void; onDelete: () => void }) { const available = !kit.activeBorrow && kit.items.length > 0 && kit.items.every((item) => item.availableQuantity > 0); return <article className="kit-card"><div className="kit-card-top"><div><p className="category">KIT · {kit.items.length} 类器材</p><h2>{kit.name}</h2></div><span className={`status ${available ? 'available' : 'borrowed'}`}>{available ? '● 可借' : kit.activeBorrow ? '● 已借出' : '● 暂不可借'}</span></div>{kit.description && <p className="description">{kit.description}</p>}<div className="kit-items">{kit.items.map((item) => <span key={item.equipmentId}>{item.equipmentName}</span>)}</div>{kit.activeBorrow && <div className="borrow-details"><span>借用人：{kit.activeBorrow.memberName}</span><span>借出时间：{formatTime(kit.activeBorrow.borrowTime)}</span></div>}<div className="card-action">{managing ? <><button className="edit" onClick={onEdit}>编辑 Kit</button><button className="delete" onClick={onDelete}>删除 Kit</button></> : mine && kit.activeBorrow ? <button className="return" onClick={onReturn}>归还整套 Kit</button> : available ? <button onClick={onBorrow}>借出整套 Kit</button> : <span>Kit 中有器材库存不足</span>}</div></article> }
function AddEquipmentDialog({ item, onClose, onSave }: { item?: Equipment; onClose: () => void; onSave: (input: EquipmentInput) => Promise<void> }) { const [name, setName] = useState(item?.name ?? ''); const [category, setCategory] = useState(item?.category ?? ''); const [quantity, setQuantity] = useState(item?.quantity ?? 1); const [description, setDescription] = useState(item?.description ?? ''); const [imageUrl, setImageUrl] = useState(item?.imageUrl ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const categories = ['相机', '镜头', '麦克风', '存储卡', '提词器', '三脚架', '电池', '滤镜', '监看器', '读卡器', '其他']; async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ name, category, quantity, description, imageUrl }) } catch (reason) { setError(reason instanceof Error ? reason.message : item ? '更新失败' : '录入失败') } finally { setBusy(false) } } return <div className="dialog-backdrop" onMouseDown={onClose}><form className="equipment-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="form-title"><h2>{item ? '编辑器材' : '录入新器材'}</h2><button type="button" onClick={onClose}>×</button></div><label>器材名称 <b>必填</b><input value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：Sony A7 IV" maxLength={200} autoFocus /></label><label>数量 <b>必填</b><input type="number" min="1" step="1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><label>类别 <small>可选，未选择归为“其他”</small><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">未选择</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>备注 <small>可选</small><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="例如：含两块电池" maxLength={500} /></label><label>图片链接 <small>可选</small><input value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="https://…" maxLength={500} /></label>{error && <p className="form-error">{error}</p>}<button className="submit-equipment" disabled={busy}>{busy ? '正在保存…' : item ? '保存修改' : '录入器材'}</button></form></div> }
function AddKitDialog({ kit, equipment, onClose, onSave }: { kit?: Kit; equipment: Equipment[]; onClose: () => void; onSave: (input: KitInput) => Promise<void> }) { const [name, setName] = useState(kit?.name ?? ''); const [description, setDescription] = useState(kit?.description ?? ''); const [selected, setSelected] = useState<number[]>(kit?.items.map((item) => item.equipmentId) ?? []); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toggle = (id: number) => setSelected((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ name, description, equipmentIds: selected }) } catch (reason) { setError(reason instanceof Error ? reason.message : kit ? '更新 Kit 失败' : '录入 Kit 失败') } finally { setBusy(false) } } return <div className="dialog-backdrop" onMouseDown={onClose}><form className="equipment-form kit-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="form-title"><h2>{kit ? '编辑 Kit' : '录入 Kit'}</h2><button type="button" onClick={onClose}>×</button></div><label>Kit 名称 <b>必填</b><input value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：采访录音套装" maxLength={200} autoFocus /></label><label>备注 <small>可选</small><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="例如：外拍采访使用" maxLength={500} /></label><fieldset><legend>包含器材 <b>至少选择一件</b></legend><div className="kit-equipment-list">{equipment.length ? equipment.map((item) => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} /><span>{item.name}<small>{item.category} · 可借 {item.availableQuantity} / {item.quantity}</small></span></label>) : <p>请先返回全部器材页，读取器材后再创建 Kit。</p>}</div></fieldset>{error && <p className="form-error">{error}</p>}<button className="submit-equipment" disabled={busy}>{busy ? '正在保存…' : kit ? '保存修改' : '创建 Kit'}</button></form></div> }
export default App
