import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { addEquipment, borrowEquipment, createMember, getEquipment, getMembers, getMyBorrowings, returnEquipment } from './api'
import type { Equipment, Member } from './types'
import './App.css'

type View = 'all' | 'available' | 'borrowed' | 'mine'
const views: { key: View; label: string }[] = [{ key: 'all', label: '全部器材' }, { key: 'available', label: '可借' }, { key: 'borrowed', label: '已借出' }, { key: 'mine', label: '我的借用' }]
const formatTime = (value: string) => new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

function App() {
  const [equipment, setEquipment] = useState<Equipment[]>([]); const [currentUser, setCurrentUser] = useState<Member | null>(null); const [view, setView] = useState<View>('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [adding, setAdding] = useState(false)
  async function loadData(user?: Member | null) { setLoading(true); setError(''); try { const [allMembers, allEquipment] = await Promise.all([getMembers(), getEquipment()]); const savedId = Number(localStorage.getItem('currentUserId')); const saved = user ?? allMembers.find((member) => member.id === savedId) ?? null; setCurrentUser(saved); setEquipment(saved && view === 'mine' ? await getMyBorrowings(saved.id) : allEquipment) } catch { setError('暂时无法读取器材数据，请稍后重试。') } finally { setLoading(false) } }
  // API 数据与浏览器存储是外部状态；初次进入和切换标签时同步读取。
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void loadData() }, [])
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { if (currentUser) void loadData(currentUser) }, [view])
  const displayed = useMemo(() => equipment.filter((item) => view === 'available' ? item.status === 'available' : view === 'borrowed' ? item.status === 'borrowed' : true), [equipment, view])
  function message(value: string) { setNotice(value); window.setTimeout(() => setNotice(''), 3200) }
  function chooseUser(member: Member) { localStorage.setItem('currentUserId', String(member.id)); localStorage.setItem('currentUserName', member.name); setCurrentUser(member); message(`你好，${member.name}！`) }
  function switchUser() { localStorage.removeItem('currentUserId'); localStorage.removeItem('currentUserName'); setCurrentUser(null); setView('all') }
  async function borrow(item: Equipment) { if (!currentUser) return; try { await borrowEquipment(item.id, currentUser.id); message(`已借出：${item.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '借出失败，请重试') } }
  async function returnItem(item: Equipment) { if (!currentUser || !item.activeBorrow) return; try { await returnEquipment(item.activeBorrow.id, currentUser.id); message(`已归还：${item.name}`); await loadData(currentUser) } catch (reason) { message(reason instanceof Error ? reason.message : '归还失败，请重试') } }
  async function saveEquipment(input: Pick<Equipment, 'name' | 'category' | 'description' | 'imageUrl'>) { try { const item = await addEquipment(input); setAdding(false); message(`已录入：${item.name}`); await loadData(currentUser) } catch (reason) { throw reason instanceof Error ? reason : new Error('录入失败，请重试') } }
  if (!currentUser && !loading) return <IdentityPicker onRegistered={chooseUser} />
  return <main className="app-shell"><header><div><p className="brand">ZJE-Lens</p><h1>器材管理系统</h1></div>{currentUser && <div className="user-area"><span>你好，<b>{currentUser.name}</b></span><button className="add-link" onClick={() => setAdding(true)}>＋ 录入器材</button><button onClick={switchUser}>切换身份</button></div>}</header><nav aria-label="器材导航">{views.map((item) => <button key={item.key} className={view === item.key ? 'selected' : ''} onClick={() => setView(item.key)}>{item.label}</button>)}</nav>{notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="关闭提示">×</button></div>}{error && <div className="error">{error}</div>}<section className="summary"><span>{view === 'mine' ? '我当前借用的器材' : views.find((item) => item.key === view)?.label}</span><strong>{loading ? '—' : displayed.length} 件</strong></section>{loading ? <p className="loading">正在读取器材…</p> : <section className="equipment-grid">{displayed.map((item) => <EquipmentCard key={item.id} item={item} mine={view === 'mine'} onBorrow={() => borrow(item)} onReturn={() => returnItem(item)} />)}</section>}{!loading && displayed.length === 0 && <div className="empty">{view === 'mine' ? '你目前没有借用中的器材。' : '这里暂时没有器材。'}</div>}{adding && <AddEquipmentDialog onClose={() => setAdding(false)} onSave={saveEquipment} />}</main>
}
function IdentityPicker({ onRegistered }: { onRegistered: (member: Member) => void }) {
  const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function register(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onRegistered(await createMember(name)) } catch (reason) { setError(reason instanceof Error ? reason.message : '注册失败，请稍后重试') } finally { setBusy(false) } }
  return <main className="identity-page"><section className="identity-card"><p className="brand">ZJE-Lens</p><h1>输入你的名字</h1><p>第一次输入会自动创建账号；以后输入相同名字即可继续。<br />这台设备会记住你的身份，你随时可以在首页切换。</p><form className="register-form single-login" onSubmit={register}><label htmlFor="new-member-name">名字 / 账号名</label><div><input id="new-member-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={100} placeholder="请输入你的名字" autoFocus /><button disabled={busy}>{busy ? '处理中…' : '继续'}</button></div>{error && <p role="alert">{error}</p>}</form></section></main>
}
function EquipmentIcon({ category }: { category: string }) {
  if (category === '相机') return <svg viewBox="0 0 80 64" aria-hidden="true"><path d="M16 18h13l5-8h12l5 8h13c5 0 8 3 8 8v24c0 5-3 8-8 8H16c-5 0-8-3-8-8V26c0-5 3-8 8-8Z" /><circle cx="40" cy="38" r="13" /><path d="M61 28h1" /></svg>
  if (category === '镜头') return <svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="23" /><path d="m37.4 22.7 13.2 22.9M26.6 22.7H53M21.3 32l13.2-22.9M26.6 41.3 13.4 18.4M37.4 41.3H11M42.7 32 29.5 54.9" /></svg>
  if (category === '麦克风') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="29" y="8" width="22" height="32" rx="11" /><path d="M21 29v2a19 19 0 0 0 38 0v-2M40 50v8M29 58h22" /></svg>
  if (['存储卡', 'SD卡', 'SD 卡', '内存卡'].includes(category)) return <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M19 7h24l9 9v41H19V7Z" /><path d="M27 7v12M35 7v12M43 7v12M25 31h21M25 40h21" /></svg>
  if (category === '提词器') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="14" y="9" width="52" height="37" rx="3" /><path d="M27 20h26M27 28h18M27 36h23M40 46v10M27 56h26" /></svg>
  if (category === '三脚架') return <svg viewBox="0 0 64 64" aria-hidden="true"><path d="M25 10h14v11H25zM32 21v14M32 35 15 57M32 35l17 22M20 57h29" /><circle cx="32" cy="35" r="3" /></svg>
  if (category === '电池') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="12" y="16" width="54" height="32" rx="3" /><path d="M66 26h5v12h-5M24 32h18M33 23v18" /></svg>
  if (category === '滤镜') return <svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="22" /><circle cx="32" cy="32" r="14" /><path d="m16.5 16.5 31 31" /></svg>
  if (['监看器', '显示器', '监视器'].includes(category)) return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="11" y="10" width="58" height="37" rx="3" /><path d="M40 47v9M26 56h28M19 19h42" /></svg>
  if (category === '读卡器') return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="14" y="15" width="52" height="35" rx="5" /><path d="M28 15v14h24V15M28 38h24" /></svg>
  return <svg viewBox="0 0 80 64" aria-hidden="true"><rect x="12" y="16" width="56" height="34" rx="3" /><path d="M12 26h56M28 16v34" /></svg>
}
function EquipmentCard({ item, mine, onBorrow, onReturn }: { item: Equipment; mine: boolean; onBorrow: () => void; onReturn: () => void }) { const borrowed = item.status === 'borrowed'; return <article className="equipment-card"><div className="card-icon"><EquipmentIcon category={item.category} /></div><div className="card-top"><div><p className="category">{item.category}</p><h2>{item.name}</h2></div><span className={`status ${borrowed ? 'borrowed' : 'available'}`}>{borrowed ? '● 已借出' : '● 可借'}</span></div>{item.description && <p className="description">{item.description}</p>}{borrowed && item.activeBorrow && <div className="borrow-details"><span>借用人：{item.activeBorrow.memberName}</span><span>借出时间：{formatTime(item.activeBorrow.borrowTime)}</span></div>}<div className="card-action">{mine && borrowed ? <button className="return" onClick={onReturn}>归还器材</button> : !borrowed ? <button onClick={onBorrow}>借出</button> : <span>暂不可借</span>}</div></article> }
function AddEquipmentDialog({ onClose, onSave }: { onClose: () => void; onSave: (input: Pick<Equipment, 'name' | 'category' | 'description' | 'imageUrl'>) => Promise<void> }) { const [name, setName] = useState(''); const [category, setCategory] = useState(''); const [description, setDescription] = useState(''); const [imageUrl, setImageUrl] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ name, category, description, imageUrl }) } catch (reason) { setError(reason instanceof Error ? reason.message : '录入失败') } finally { setBusy(false) } } return <div className="dialog-backdrop" onMouseDown={onClose}><form className="equipment-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="form-title"><h2>录入新器材</h2><button type="button" onClick={onClose}>×</button></div><label>器材名称 <b>必填</b><input value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：Sony A7 IV" maxLength={200} autoFocus /></label><label>类别 <small>可选，未填为“其他”</small><input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="例如：相机" maxLength={100} /></label><label>备注 <small>可选</small><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="例如：含两块电池" maxLength={500} /></label><label>图片链接 <small>可选</small><input value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="https://…" maxLength={500} /></label>{error && <p className="form-error">{error}</p>}<button className="submit-equipment" disabled={busy}>{busy ? '正在保存…' : '录入器材'}</button></form></div> }
export default App
