import type { BorrowRecord, Equipment, EquipmentInput, Kit, KitInput, KitBorrowRecord, Member, TaskInput, TeamTask } from './types'
// 第一阶段的本地临时数据；页面只通过 api.ts 访问它，未来可直接换成 HTTP API。
const members: Member[] = [{ id: 1, name: 'Bowen' }, { id: 2, name: 'Alice' }, { id: 3, name: 'Bob' }]
// mock 模式页面刷新时会重置内存；仅据现有身份补回成员，不保存任何器材或借还数据。
const savedId = Number(localStorage.getItem('currentUserId'))
const savedName = localStorage.getItem('currentUserName')?.trim()
if (Number.isInteger(savedId) && savedId > 0 && savedName && !members.some((member) => member.id === savedId)) members.push({ id: savedId, name: savedName })
const equipment: Equipment[] = [{ id: 1, name: 'Sony ZV-E1', category: '相机', status: 'available', quantity: 1, availableQuantity: 1, activeBorrowCount: 0, description: '全画幅 Vlog 相机，含电池与存储卡。' }, { id: 2, name: 'Sony 24–70 GM II', category: '镜头', status: 'available', quantity: 1, availableQuantity: 1, activeBorrowCount: 0, description: 'F2.8 标准变焦镜头。' }, { id: 3, name: 'DJI Mic 2', category: '麦克风', status: 'borrowed', quantity: 1, availableQuantity: 0, activeBorrowCount: 1, description: '双通道无线麦克风套装。', activeBorrow: { id: 1, equipmentId: 3, memberId: 2, memberName: 'Alice', borrowTime: '2026-08-27T12:30:00.000Z', returnTime: null } }]
let records: BorrowRecord[] = equipment.flatMap((item) => item.activeBorrow ? [item.activeBorrow] : [])
let tasks: TeamTask[] = []
let kits: Kit[] = []
const kitBorrowRecords: KitBorrowRecord[] = []
const realChineseNamePattern = /^\p{Script=Han}{2,6}$/u
const wait = () => new Promise((resolve) => setTimeout(resolve, 180)); const copy = <T,>(data: T): T => JSON.parse(JSON.stringify(data)) as T
const activeRecordsFor = (equipmentId: number) => records.filter((record) => record.equipmentId === equipmentId && !record.returnTime)
const refreshEquipment = (item: Equipment) => { const activeBorrows = activeRecordsFor(item.id); item.activeBorrowCount = activeBorrows.length; item.availableQuantity = Math.max(0, item.quantity - activeBorrows.length); item.status = item.availableQuantity > 0 ? 'available' : 'borrowed'; item.activeBorrow = activeBorrows[0] ?? null; item.activeBorrows = activeBorrows }
const refreshAllEquipment = () => equipment.forEach(refreshEquipment)
export async function listMembers() { await wait(); return copy(members) }; export async function listEquipment() { await wait(); refreshAllEquipment(); return copy(equipment) }; export async function listMyBorrowings(memberId: number) { await wait(); refreshAllEquipment(); return copy(records.filter((record) => record.memberId === memberId && !record.returnTime).map((record) => ({ ...equipment.find((item) => item.id === record.equipmentId)!, activeBorrow: record, activeBorrows: [record] }))) }
export async function listBorrowHistory() { await wait(); return copy(records.map((record) => { const item = equipment.find((value) => value.id === record.equipmentId); return { ...record, equipmentName: item?.name ?? '已删除器材', equipmentCategory: item?.category ?? '其他' } }).sort((a, b) => b.borrowTime.localeCompare(a.borrowTime))) }
export async function listMemberBorrowHistory(memberId: number) { const history = await listBorrowHistory(); return history.filter((record) => record.memberId === memberId) }
export async function registerMember(name: string) { await wait(); const trimmed = name.trim(); if (!realChineseNamePattern.test(trimmed)) throw new Error('请输入 2–6 个中文汉字'); const existing = members.find((member) => member.name === trimmed); if (existing) return copy(existing); const member = { id: Math.max(...members.map((item) => item.id)) + 1, name: trimmed }; members.push(member); return copy(member) }
export async function createEquipment(input: EquipmentInput) { await wait(); const name = input.name.trim(); if (!name) throw new Error('请填写器材名称'); const quantity = Number(input.quantity); if (!Number.isInteger(quantity) || quantity < 1) throw new Error('数量必须是大于 0 的整数'); const item: Equipment = { id: Math.max(...equipment.map((value) => value.id)) + 1, name, category: input.category?.trim() || '其他', description: input.description?.trim() || null, imageUrl: input.imageUrl?.trim() || null, status: 'available', quantity, availableQuantity: quantity, activeBorrowCount: 0, activeBorrows: [] }; equipment.push(item); return copy(item) }
export async function updateEquipment(id: number, input: EquipmentInput) { await wait(); const item = equipment.find((value) => value.id === id); if (!item) throw new Error('器材不存在'); const name = input.name.trim(); if (!name) throw new Error('请填写器材名称'); const quantity = Number(input.quantity); const activeCount = activeRecordsFor(id).length; if (!Number.isInteger(quantity) || quantity < 1) throw new Error('数量必须是大于 0 的整数'); if (quantity < activeCount) throw new Error(`当前仍有 ${activeCount} 件借出中，数量不能低于此数`); item.name = name; item.category = input.category?.trim() || '其他'; item.description = input.description?.trim() || null; item.imageUrl = input.imageUrl?.trim() || null; item.quantity = quantity; refreshEquipment(item); return copy(item) }
export async function listKits() { await wait(); refreshAllEquipment(); return copy(kits.map((kit) => ({ ...kit, items: kit.items.map((entry) => { const item = equipment.find((value) => value.id === entry.equipmentId); return item ? { equipmentId: item.id, equipmentName: item.name, equipmentCategory: item.category, status: item.status, quantity: item.quantity, availableQuantity: item.availableQuantity } : entry }), activeBorrow: kitBorrowRecords.find((record) => record.kitId === kit.id && !record.returnTime) ?? null }))) }
export async function createKit(input: KitInput) { await wait(); const name = input.name.trim(); const ids = [...new Set(input.equipmentIds)]; if (!name) throw new Error('请填写 Kit 名称'); if (!ids.length) throw new Error('请至少选择一件器材'); const items = ids.map((id) => equipment.find((item) => item.id === id)).filter((item): item is Equipment => Boolean(item)); if (items.length !== ids.length) throw new Error('部分器材不存在'); const kit: Kit = { id: Date.now(), name, description: input.description.trim() || null, items: items.map((item) => ({ equipmentId: item.id, equipmentName: item.name, equipmentCategory: item.category, status: item.status, quantity: item.quantity, availableQuantity: item.availableQuantity })), activeBorrow: null }; kits = [kit, ...kits]; return copy(kit) }
export async function updateKit(id: number, input: KitInput) { await wait(); const kit = kits.find((item) => item.id === id); const name = input.name.trim(); const ids = [...new Set(input.equipmentIds)]; if (!kit) throw new Error('Kit 不存在'); if (kitBorrowRecords.some((record) => record.kitId === id && !record.returnTime)) throw new Error('Kit 正在借出，归还后才能编辑'); if (!name) throw new Error('请填写 Kit 名称'); if (!ids.length) throw new Error('请至少选择一件器材'); const items = ids.map((equipmentId) => equipment.find((item) => item.id === equipmentId)).filter((item): item is Equipment => Boolean(item)); if (items.length !== ids.length) throw new Error('部分器材不存在'); kit.name = name; kit.description = input.description.trim() || null; kit.items = items.map((item) => ({ equipmentId: item.id, equipmentName: item.name, equipmentCategory: item.category, status: item.status, quantity: item.quantity, availableQuantity: item.availableQuantity })); return copy(kit) }
export async function deleteKit(id: number) { await wait(); const index = kits.findIndex((item) => item.id === id); if (index < 0) throw new Error('Kit 不存在'); if (kitBorrowRecords.some((record) => record.kitId === id)) throw new Error('Kit 正在借出或已有借还历史，无法删除'); kits.splice(index, 1) }
export async function borrowKit(kitId: number, memberId: number) { await wait(); refreshAllEquipment(); const kit = kits.find((item) => item.id === kitId); const member = members.find((item) => item.id === memberId); if (!kit || !member) throw new Error('Kit 或成员不存在'); if (kitBorrowRecords.some((record) => record.kitId === kitId && !record.returnTime)) throw new Error('该 Kit 已被借出'); const items = kit.items.map((entry) => equipment.find((item) => item.id === entry.equipmentId)).filter((item): item is Equipment => Boolean(item)); if (items.length !== kit.items.length || items.some((item) => item.availableQuantity < 1)) throw new Error('Kit 中有器材库存不足，暂时无法整套借出'); const kitRecord: KitBorrowRecord = { id: Date.now(), kitId, memberId, memberName: member.name, borrowTime: new Date().toISOString(), returnTime: null }; kitBorrowRecords.push(kitRecord); for (const item of items) { const record: BorrowRecord = { id: Date.now() + item.id, equipmentId: item.id, memberId, memberName: member.name, borrowTime: kitRecord.borrowTime, returnTime: null, kitBorrowRecordId: kitRecord.id }; records = [...records, record]; refreshEquipment(item) } }
export async function returnKit(kitBorrowRecordId: number, memberId: number) { await wait(); const kitRecord = kitBorrowRecords.find((record) => record.id === kitBorrowRecordId && !record.returnTime); if (!kitRecord || kitRecord.memberId !== memberId) throw new Error('未找到你的有效 Kit 借用记录'); const returnTime = new Date().toISOString(); kitRecord.returnTime = returnTime; records.filter((record) => record.kitBorrowRecordId === kitBorrowRecordId && !record.returnTime).forEach((record) => { record.returnTime = returnTime }); refreshAllEquipment() }
export async function deleteEquipment(id: number) { await wait(); const index = equipment.findIndex((item) => item.id === id); if (index < 0) throw new Error('器材不存在'); if (equipment[index].status === 'borrowed' || records.some((record) => record.equipmentId === id)) throw new Error('器材正在借出或已有借还历史，无法删除'); equipment.splice(index, 1) }
export async function borrow(equipmentId: number, memberId: number) { await wait(); const item = equipment.find((value) => value.id === equipmentId); const member = members.find((value) => value.id === memberId); if (!item || !member) throw new Error('器材或成员不存在'); refreshEquipment(item); if (item.availableQuantity < 1) throw new Error('这类器材已经全部借出'); const record: BorrowRecord = { id: Date.now(), equipmentId, memberId, memberName: member.name, borrowTime: new Date().toISOString(), returnTime: null }; records = [...records, record]; refreshEquipment(item) }
export async function returnBorrow(recordId: number, memberId: number) { await wait(); const record = records.find((value) => value.id === recordId && !value.returnTime); if (!record || record.memberId !== memberId) throw new Error('未找到你的有效借用记录'); const item = equipment.find((value) => value.id === record.equipmentId); if (!item) throw new Error('器材不存在'); record.returnTime = new Date().toISOString(); refreshEquipment(item) }
export async function returnAllBorrowings(memberId: number) { await wait(); const activeRecords = records.filter((record) => record.memberId === memberId && !record.returnTime); const activeKits = kitBorrowRecords.filter((record) => record.memberId === memberId && !record.returnTime); if (!activeRecords.length && !activeKits.length) throw new Error('你当前没有需要归还的器材'); const returnTime = new Date().toISOString(); activeKits.forEach((record) => { record.returnTime = returnTime }); activeRecords.forEach((record) => { record.returnTime = returnTime }); refreshAllEquipment() }
export async function listTasks(archived = false) { await wait(); return copy(tasks.filter((task) => Boolean(task.archivedAt) === archived).map((task) => ({ ...task, equipment: records.filter((record) => !record.returnTime && task.participants.some((participant) => participant.memberId === record.memberId)).map((record) => { const item = equipment.find((value) => value.id === record.equipmentId)!; return { equipmentId: item.id, equipmentName: item.name, equipmentCategory: item.category, memberId: record.memberId, memberName: record.memberName } }) }))) }
export async function createTask(input: TaskInput, memberId: number) { await wait(); const title = input.title.trim(); if (!title) throw new Error('请填写任务名称'); const member = members.find((item) => item.id === memberId); if (!member) throw new Error('成员不存在'); const task: TeamTask = { id: Date.now(), title, taskTime: input.taskTime || null, location: input.location?.trim() || null, note: input.note?.trim() || null, createdByName: member.name, createdAt: new Date().toISOString(), archivedAt: null, participants: [], equipment: [] }; tasks = [task, ...tasks]; return copy(task) }
export async function updateTask(id: number, input: TaskInput) { await wait(); const task = tasks.find((item) => item.id === id); if (!task) throw new Error('任务不存在'); const title = input.title.trim(); if (!title) throw new Error('请填写任务名称'); task.title = title; task.taskTime = input.taskTime || null; task.location = input.location?.trim() || null; task.note = input.note?.trim() || null; return copy(task) }
export async function joinTask(id: number, memberId: number) { await wait(); const task = tasks.find((item) => item.id === id); const member = members.find((item) => item.id === memberId); if (!task || !member) throw new Error('任务或成员不存在'); if (task.participants.some((item) => item.memberId === memberId)) throw new Error('你已经参与了此任务'); task.participants.push({ memberId, memberName: member.name, joinedAt: new Date().toISOString() }) }
export async function leaveTask(id: number, memberId: number) { await wait(); const task = tasks.find((item) => item.id === id); if (!task) throw new Error('任务不存在'); const index = task.participants.findIndex((item) => item.memberId === memberId); if (index < 0) throw new Error('你尚未参与此任务'); task.participants.splice(index, 1) }
export async function archiveTask(id: number) { await wait(); const task = tasks.find((item) => item.id === id); if (!task) throw new Error('任务不存在'); task.archivedAt = new Date().toISOString() }
export async function deleteTask(id: number) { await wait(); const index = tasks.findIndex((item) => item.id === id); if (index < 0) throw new Error('任务不存在'); tasks.splice(index, 1) }
