import type { BorrowRecord, Equipment, Member } from './types'
// 第一阶段的本地临时数据；页面只通过 api.ts 访问它，未来可直接换成 HTTP API。
const members: Member[] = [{ id: 1, name: 'Bowen' }, { id: 2, name: 'Alice' }, { id: 3, name: 'Bob' }]
// mock 模式页面刷新时会重置内存；仅据现有身份补回成员，不保存任何器材或借还数据。
const savedId = Number(localStorage.getItem('currentUserId'))
const savedName = localStorage.getItem('currentUserName')?.trim()
if (Number.isInteger(savedId) && savedId > 0 && savedName && !members.some((member) => member.id === savedId)) members.push({ id: savedId, name: savedName })
const equipment: Equipment[] = [{ id: 1, name: 'Sony ZV-E1', category: '相机', status: 'available', description: '全画幅 Vlog 相机，含电池与存储卡。' }, { id: 2, name: 'Sony 24–70 GM II', category: '镜头', status: 'available', description: 'F2.8 标准变焦镜头。' }, { id: 3, name: 'DJI Mic 2', category: '麦克风', status: 'borrowed', description: '双通道无线麦克风套装。', activeBorrow: { id: 1, equipmentId: 3, memberId: 2, memberName: 'Alice', borrowTime: '2026-08-27T12:30:00.000Z', returnTime: null } }]
let records: BorrowRecord[] = equipment.flatMap((item) => item.activeBorrow ? [item.activeBorrow] : [])
const wait = () => new Promise((resolve) => setTimeout(resolve, 180)); const copy = <T,>(data: T): T => JSON.parse(JSON.stringify(data)) as T
export async function listMembers() { await wait(); return copy(members) }; export async function listEquipment() { await wait(); return copy(equipment) }; export async function listMyBorrowings(memberId: number) { await wait(); return copy(equipment.filter((item) => item.activeBorrow?.memberId === memberId)) }
export async function registerMember(name: string) { await wait(); const trimmed = name.trim(); if (!trimmed) throw new Error('请输入名字'); const existing = members.find((member) => member.name.toLocaleLowerCase() === trimmed.toLocaleLowerCase()); if (existing) return copy(existing); const member = { id: Math.max(...members.map((item) => item.id)) + 1, name: trimmed }; members.push(member); return copy(member) }
export async function createEquipment(input: Pick<Equipment, 'name' | 'category' | 'description' | 'imageUrl'>) { await wait(); const name = input.name.trim(); if (!name) throw new Error('请填写器材名称'); const item: Equipment = { id: Math.max(...equipment.map((value) => value.id)) + 1, name, category: input.category?.trim() || '其他', description: input.description?.trim() || null, imageUrl: input.imageUrl?.trim() || null, status: 'available' }; equipment.push(item); return copy(item) }
export async function deleteEquipment(id: number) { await wait(); const index = equipment.findIndex((item) => item.id === id); if (index < 0) throw new Error('器材不存在'); if (equipment[index].status === 'borrowed' || records.some((record) => record.equipmentId === id)) throw new Error('器材正在借出或已有借还历史，无法删除'); equipment.splice(index, 1) }
export async function borrow(equipmentId: number, memberId: number) { await wait(); const item = equipment.find((value) => value.id === equipmentId); const member = members.find((value) => value.id === memberId); if (!item || !member) throw new Error('器材或成员不存在'); if (item.status !== 'available') throw new Error('这件器材刚刚被其他成员借走了'); const record: BorrowRecord = { id: Date.now(), equipmentId, memberId, memberName: member.name, borrowTime: new Date().toISOString(), returnTime: null }; item.status = 'borrowed'; item.activeBorrow = record; records = [...records, record] }
export async function returnBorrow(recordId: number, memberId: number) { await wait(); const record = records.find((value) => value.id === recordId && !value.returnTime); if (!record || record.memberId !== memberId) throw new Error('未找到你的有效借用记录'); const item = equipment.find((value) => value.id === record.equipmentId); if (!item) throw new Error('器材不存在'); record.returnTime = new Date().toISOString(); item.status = 'available'; item.activeBorrow = null }
