export type EquipmentStatus = 'available' | 'borrowed'
export type Member = { id: number; name: string }
export type BorrowRecord = { id: number; equipmentId: number; equipmentName?: string; equipmentCategory?: string; memberId: number; memberName: string; borrowTime: string; returnTime: string | null; kitBorrowRecordId?: number | null }
export type Equipment = { id: number; name: string; category: string; status: EquipmentStatus; quantity: number; availableQuantity: number; activeBorrowCount: number; imageUrl?: string | null; description?: string | null; activeBorrow?: BorrowRecord | null; activeBorrows?: BorrowRecord[] }
export type EquipmentInput = Pick<Equipment, 'name' | 'category' | 'description' | 'imageUrl' | 'quantity'>
export type KitItem = { equipmentId: number; equipmentName: string; equipmentCategory: string; status: EquipmentStatus; quantity: number; availableQuantity: number }
export type KitBorrowRecord = { id: number; kitId: number; memberId: number; memberName: string; borrowTime: string; returnTime: string | null }
export type Kit = { id: number; name: string; description: string | null; items: KitItem[]; activeBorrow: KitBorrowRecord | null }
export type KitInput = { name: string; description: string; equipmentIds: number[] }
export type BorrowCommandEquipment = { equipmentId: number; name: string; category: string; quantity: number; availableQuantity: number; confidence: number }
export type BorrowCommandKit = { kitId: number; name: string; itemCount: number; available: boolean; confidence: number }
export type BorrowCommandResult = { transcript: string; equipment: BorrowCommandEquipment[]; kits: BorrowCommandKit[]; unresolvedItems: string[] }
export type BatchBorrowInput = { memberId: number; items: { equipmentId: number; quantity: number }[]; kitIds: number[] }
export type BatchBorrowResult = { ok: true; borrowedEquipmentCount: number; borrowedKitCount: number }
export type SpeechToken = { token: string; region: string }
export type TaskParticipant = { memberId: number; memberName: string; joinedAt: string }
export type TaskEquipment = { equipmentId: number; equipmentName: string; equipmentCategory: string; memberId: number; memberName: string }
export type TeamTask = { id: number; title: string; taskTime: string | null; location: string | null; note: string | null; createdByName: string | null; createdAt: string; archivedAt: string | null; participants: TaskParticipant[]; equipment: TaskEquipment[] }
export type TaskInput = Pick<TeamTask, 'title' | 'taskTime' | 'location' | 'note'>
